name: aneurysm_cnn_rocm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # 3.10 is widely compatible with PyTorch 2.3 + ROCm 6.0
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - matplotlib
  - nibabel
  - pip
  
  - pip:
    # Strictly target ROCm 6.0 to match your cluster drivers
    - --index-url https://download.pytorch.org/whl/rocm6.0
    - torch==2.3.1
    - torchvision==0.18.1
    - monai